{{- include "_config.load" $ }}
{{- $root := . }}
{{- if .Values.features.ingress.self_signed }}
---
apiVersion: quarks.cloudfoundry.org/v1alpha1
kind: QuarksSecret
metadata:
  name: {{ .Release.Name }}-ingress-tls-ca
  namespace: {{ .Release.Namespace | quote }}
spec:
  request:
    certificate:
      alternativeNames: null
      commonName: {{ .Values.system_domain }}
      isCA: true
      signerType: local
  secretName: {{ .Release.Name }}-ingress-tls-ca
  type: certificate
---
apiVersion: quarks.cloudfoundry.org/v1alpha1
kind: QuarksSecret
metadata:
  name: {{ .Release.Name }}-ingress-tls
  namespace: kubecf
spec:
  request:
    certificate:
      CAKeyRef:
        key: private_key
        name: {{ .Release.Name }}-ingress-tls-ca
      CARef:
        key: certificate
        name: {{ .Release.Name }}-ingress-tls-ca
      alternativeNames:
      - "*.{{ .Values.system_domain }}"
      commonName: kubeTlsTypeCert
      isCA: false
      signerType: local
  secretName: {{ .Release.Name }}-ingress-tls
  type: tls
{{- end }}
